const basePath = "/assets";

export const assets = {
  logo: `${basePath}/vdtech-logo.svg`,
  heroImg: `${basePath}/hero-Image.svg`,
  whoWeAreImg: `${basePath}/whoWeAre-img.svg`,
  arrowRight: `${basePath}/arr-right.svg`,
  project1: `${basePath}/project-1.svg`,
  project2: `${basePath}/project-2.svg`,
  project3: `${basePath}/project-3.svg`,
  arrowImg: `${basePath}/Arrow 1.svg`,
  patternImg: `${basePath}/Pattern.svg`,
  client1: `${basePath}/clients1.svg`,
  client2: `${basePath}/clients2.svg`,
  client3: `${basePath}/clients3.svg`,
  ourStoryImg: `${basePath}/ourStoryImg.svg`,
  planImg: `${basePath}/planImg.webp`,
  aboutBgImg: `${basePath}/aboutBg.svg`,
  valueIcon1: `${basePath}/valueIcon-1.svg`,
  valueIcon2: `${basePath}/valueIcon-2.svg`,
  valueIcon3: `${basePath}/valueIcon-3.svg`,
  valueIcon4: `${basePath}/valueIcon-4.svg`,
  valueIcon5: `${basePath}/valueIcon-5.svg`,
  valueIcon6: `${basePath}/valueIcon-6.svg`,
  achievementImg1: `${basePath}/achievmentImg-1.svg`,
  achievementImg2: `${basePath}/achievmentImg-2.svg`,
  achievementImg3: `${basePath}/achievmentImg-3.svg`,
  achievementImg4: `${basePath}/achievmentImg-4.svg`,
  teamImg1: `${basePath}/victor-dp.jpg`,
  teamImg2: `${basePath}/divine-dp.jpeg`,
  servicesIcon1: `${basePath}/servicesIcon-1.svg`,
  servicesIcon2: `${basePath}/servicesIcon-2.svg`,
  servicesIcon3: `${basePath}/servicesIcon-3.svg`,
  servicesIcon4: `${basePath}/servicesIcon-4.svg`,
  servicesIcon5: `${basePath}/servicesIcon-5.svg`,
  servicesIcon6: `${basePath}/servicesIcon-6.svg`,
  joinUsImg: `${basePath}/JoinUs-img.svg`,
};

export default assets;
